run: ppo
stop:
    training_iteration: 2000
custom_metrics:
- c_viol_r
- c_viol_v
- c_viol_s
- mf
- epsilon
postproc_data:
    episode_step_data: 
    - t
    - x
    - y
    - z
    - vx
    - vy
    - vz
    - m
    - fx
    - fy
    - fz
    - fnorm
    episode_end_data: 
    - x0
    - y0
    - z0
    - vx0
    - vy0
    - vz0
    - xf
    - yf
    - zf
    - vxf
    - vyf
    - vzf
    - tf
    - xNN
    - yNN
    - zNN
    - vxNN
    - vyNN
    - vzNN
    - xCP
    - yCP
    - zCP
    - vxCP
    - vyCP
    - vzCP
    - dist
num_eval_episodes: 1
eval_env_config:
    env_config:
        prng_seed: 0
config:
    num_workers: 10
    num_envs_per_worker: 6
    num_gpus: 0
    num_cpus_per_worker: 0.6
    num_gpus_per_worker: 0
    num_cpus_for_driver: 1
    rollout_fragment_length: 100
    batch_mode: complete_episodes
    train_batch_size: 30000
    model:
        fcnet_hiddens: [70, 46, 30]
        fcnet_activation: tanh
        use_lstm: False
        vf_share_layers: False
        free_log_std: True
    gamma: 1.
    log_level: INFO
    framework: tf
    explore: True
    ignore_worker_failures: True
    evaluation_parallel_to_training: True
    evaluation_interval: 1
    evaluation_duration: 1
    evaluation_duration_unit: episodes
    evaluation_config:
        explore: False
        env_config:
            eps_schedule: [[0, 1.0e-03], [1, 1.0e-03]]
    evaluation_num_workers: 0
    always_attach_evaluation_results: True
    use_critic: True
    use_gae: True
    lambda: 1.
    kl_coeff: 0.
    sgd_minibatch_size: 3000
    shuffle_sequences: True
    num_sgd_iter: 40
    lr: 1.0e-04
    # lr_schedule: [[0, 1.0e-04], [60000000, 1.0e-06]]
    vf_loss_coeff: 0.5
    clip_param: 0.05
    vf_clip_param: 1.
    env: environment.cislunar_env.CislunarEnv
    env_config:
        planar: True
        action_type: 1
        randomIC: False
        pertIC: False
        nav_errors: False
        fixed_point_f: False
        H: 100
        eps_schedule: [[0, 1.0e-03], [2000, 1.0e-03]]
        eta: 0.1
        fmax: 4.0e-02
        Isp: 3000.
        tf: 6
        m0: 1
        r0_in: [0.81040000, 0.00000000, 0.00000000]
        v0_in: [0.00000000, 0.26810296, 0.00000000]
        T_in: 2.97713600
        r0_f: [1.19100000, 0.00000000, 0.00000000]
        v0_f: [0.00000000, -0.23731331, 0.00000000]
        T_f: 3.49375051
        dr0_max: [0., 0., 0.]
        dv0_max: [0., 0., 0.]
        sigma_r: [0., 0., 0.]
        sigma_v: [0., 0., 0.]
        sigma_m: 0.
    callbacks:
        epsConstraintCallbacks
